//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApplication.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ceit_gwa_databaseEntities1 : DbContext
    {
        public ceit_gwa_databaseEntities1()
            : base("name=ceit_gwa_databaseEntities1")
        {
            //Database.SetInitializer<ceit_gwa_databaseEntities1>(new CreateDatabaseIfNotExists<ceit_gwa_databaseEntities1>());
            //Database.Initialize(true);
            //Database.SetInitializer(new DatabaseInitializer());
            //Database.SetInitializer(new MigrateDatabaseToLatestVersion<ceit_gwa_databaseEntities1, Migrations.Configuration>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CeitAdministrator> CeitAdministrators { get; set; }
        public virtual DbSet<CeitCourse> CeitCourses { get; set; }
        public virtual DbSet<CeitSecurityQuestion> CeitSecurityQuestions { get; set; }
        public virtual DbSet<CeitStudent> CeitStudents { get; set; }
        public virtual DbSet<CeitUserRole> CeitUserRoles { get; set; }
        public virtual DbSet<CeitUser> CeitUsers { get; set; }
        public virtual DbSet<CeitYearLevel> CeitYearLevels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
