//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CeitUser
    {
        [Key]
        public int UserId { get; set; }
        public string StudentAccount { get; set; }
        public string Password { get; set; }
        public int? Roles { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateUpdated { get; set; }
        public string LoginAccount { get; set; }
        public string AdminAccount { get; set; }
    
        public virtual CeitAdministrator CeitAdministrator { get; set; }
        public virtual CeitStudent CeitStudent { get; set; }
        public virtual CeitUserRole CeitUserRole { get; set; }
    }
}
